version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/capstone-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=your_db_password
      - JWT_SECRET=V3ryS3cretJwtKeyForAuthenticat10n123!
      - STRIPE_SECRET_KEY=sk_test_...
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: capstone-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_db_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: